### ISSUE TITLE
Build pipeline from configuration file

### ISSUE THREAD

**Issue by anibalsolon** [radiome-lab/radiome#26]
Given a YAML file containing the pipeline definition, wire up the respective workflows.

For now, consider the order it shows up in the YAML as the order it should be build.

E.g.
Consider two schemas for the workflow `radiome.workflows.skullstripping.afni` and workflow `radiome.workflows.bias_field_correction`:

```yaml
# radiome.workflows.skullstripping.afni
spatial_normalization: bool
```

```yaml
# radiome.workflows.bias_field_correction
histogram_sharpening: float
```

The workflows are configured and tied together in a pipeline config, each of them following its own schema:

```yaml
# pipeline configuration .yaml (that will be validated with the schemas)
radiome.workflows.skullstripping.afni:
    spatial_normalization: yes
radiome.workflows.bias_field_correction:
    histogram_sharpening: 10.4
```
