### ISSUE TITLE
Pipeline config file specification

### ISSUE THREAD

**Issue by anibalsolon** [radiome-lab/radiome#31]
Related to #26 

The way it is at the moment is a dictionary of plugins, containing its configurations:

```
# pipeline configuration .yaml (that will be validated with the schemas)
radiome.workflows.skullstripping.afni:
    spatial_normalization: yes
radiome.workflows.bias_field_correction:
    histogram_sharpening: 10.4
```

Some things to consider:
- the plugins can come from different sources, like github, e.g. `gh://radiome-lab/radiome/radiome.workflows.bias_field_correction`
- I am not sure if we should include execution information in the pipeline or in a different yaml e.g. ssh machine access
