### ISSUE TITLE
Workflow Template and CLI proposal

### ISSUE THREAD

**Issue by puorc** [radiome-lab/radiome#47]
## Workflow Template
The workflow template is a cookiecutter template:

```
- doc
- test
- {{Package name}}
     - workflow.py
- spec.yml
```

`workflow.py` is the entry point of the workflow, it must have a function `create_workflow(config: dict, resource_pool: ResourcePool, context: dict) -> None`, where `config` has the parameters from the pipeline builder config. For reference,  a typical pipeline builder config is

```
# pipeline configuration .yaml (that will be validated with the schemas)
radiome.workflows.skullstripping.afni:
    spatial_normalization: yes
radiome.workflows.bias_field_correction:
    histogram_sharpening: 10.4
```
`resource_pool` is where original and processed image files reside, resources are resolved at run-time.  `context` contains other information provided by the pipeline builder at run-time, such as available system resource, working directory, etc.

To enable a single workflow to run independently, a wrapper CLI of `create_workflow` is needed, which can read `config` from file, mock `context`, transform `ResourceKey:Pathlike` mapping into in-memory `resource pool`, eventually run `create_workflow`, and move result files to the destination.

`spec.yml` is for the description of inputs, outputs, environments and other meta information. 

It is worth noting that there are conceptually four kinds of config data.
1. the input schema for a workflow.
2. the concrete input values for a workflow.
3. meta and environments (for test purpose) information for a workflow.
4. the information on combining workflows, i.e. pipeline builder config.

I came up with three ways to organize them. It depends on how much control we will impose on a single workflow.

### Current implementation
The author of a workflow is free to implement schema, validation, test environment set-up, CLI and so on. The workflow is valid as long as there is `create_workflow` in the `workflow.py`. All information on (1), (3) is out of our scope.

### Common Workflow Language implementation

Common Workflow Language (https://www.commonwl.org/) is a standard of YAML description on executing command line tools in a specific order. It provides inputs validation(of primitive types, records, and Files) and binding(to flags of command line), outputs to files, the connection of steps by inputs parameters and output files. There is an example:

```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow
inputs:
  tarball: File
  name_of_file_to_extract: string

outputs:
  compiled_class:
    type: File
    outputSource: compile/classfile

steps:
  untar:
    run: tar-param.cwl
    in:
      tarfile: tarball
      extractfile: name_of_file_to_extract
    out: [extracted_file]

  compile:
    run: arguments.cwl
    in:
      src: untar/extracted_file
    out: [classfile]
```
And the concrete input values come from a separate YAML file:
```
tarball:
  class: File
  path: hello.tar
name_of_file_to_extract: Hello.java
```
If we can put every single workflow in a separate yaml file like this:
```yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool

label: AFNI Skullstrip Tool.
doc: AFNI Skullstrip tool for Radiome.

baseCommand: cli.py
requirements:
  ResourceRequirement:
    coresMax: 1
    ramMin: 4096
  SchemaDefRequirement:
    types:
      - $import: radiome-types.yaml
      
hints:
  DockerRequirement:
    dockerPull: Radiome:Image
    
inputs:
  spatial_normalization:
    type: Boolean
    inputBinding:
        prefix: --spatial_normalization
  resource_pool:
    type: ResourcePool
    inputBinding:
        prefix: --pool
  context:
 		type: RadiomeContext
 		inputBinding:
 			prefix: --context
 			
outputs:
  out_image:
    type: File
    outputBinding:
        glob: SOME_BIDS_NAME.nii.gz
        
s:author:
  - class: s:Person
    s:identifier: https://id.org
    s:email: mailto:abc@gmail.com
    s:name: Somebody

s:contributor:
  - class: s:Person
    s:identifier: https://id.org
    s:email: mailto:dec@gmail.com
    s:name: Someone

s:citation: https://dx.doi.org/abcde
s:codeRepository: https://github.com/radiome/xxx.git
s:dateCreated: "2020-02-10"
s:license: https://spdx.org/licenses/Apache-2.0 
```

Then we may be able to describe the pipeline builder file:

```yaml
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: Workflow

inputs:
    bids_inputs:
        type: Directory
    
outputs:
    bids_outputs:
        type: Directory

steps:
  initial:
    run: initial.cwl
    in:
      non_local_means_filtering: True
      n4_bias_field_correction: False
    out: [bids_outputs/label-intial-T1w]  
  skullstrip:
    run: skullstrip-afni.cwl
    in:
      shrink_factor: 1.0
    out: [bids_outputs/label-skullstrip-T1w] 
```

If our template can conform to the CWL standard, then we can take advantage of the growing CWL ecosystem and tools. However, it is difficult in practice:

1. The execution model is different. The cwl-runner mainly pass in parameters to command-line tools and use files to communicate between different steps. This may fit in the single workflow execution partially but not pipeline building.
2. Some notions may be specific to our needs but not supported in the standard.
3. Based on (1)(2), to do our job and conform to the CWL standard, we need to modify the cwl-tools and alter its behavior. But the documentation provides very little detail on that. The cwl-tool is poorly componentized and lacks a clear boundary between front-end(parser) and backend(execution).

### Mixed implementation

If supporting the entire set of CWL standard is not feasible, we can start with a subset of its features. The schema `spec.yml` for a single workflow is:

 ```yaml
radiomeSchemaVersion: v1.0

# Describe the type of schema and how to execute, required.
class: Workflow

# Name of the workflow. required.
name: initial-processing

# A short descriptive documentation. optional.
doc: Reorient and resample the anatomical images.

# Other useful information. optional.
s:author:
  - class: s:Person
    s:identifier: https://id.org
    s:email: mailto:abc@gmail.com
    s:name: Somebody

s:contributor:
  - class: s:Person
    s:identifier: https://id.org
    s:email: mailto:dec@gmail.com
    s:name: Someone

s:citation: https://dx.doi.org/abcde
s:codeRepository: https://github.com/radiome/xxx.git
s:dateCreated: "2020-02-10"
s:license: https://spdx.org/licenses/Apache-2.0 

# Requirements for executing this workflow, optional.
requirements:
  DockerRequirement:
      # Run in docker, support five types of input
      # dockerPull: Specify a Docker image to retrieve using docker pull.
      # dockerLoad: Specify a HTTP URL from which to download a Docker image using docker load.
      # dockerFile: Supply the contents of a Dockerfile which will be built using docker build.
      # dockerImageId: The image id that will be used for docker run. 
  ResourceRequirement:
    coresMin: 1
    ramMin: 2048
    tmpdirMin: 100
    outdirMin: 200

# Entry point, required if there are no steps.
entry: ./src/workflow.py

# Input schema, fully compatible with Python cerberus
# Use cerberus because its schema can be serialized into yaml file
inputs:
  # Implicit, can be resolved either run-time or from file.
  resource_pool:
    type: ResourcePool
  context:
    type: Context
    # Explicit.
  non_local_means_filtering:
    type: boolean
    doc: enable non local means.
  n4_bias_field_correction:
    type: boolean
    doc: enable n4 bias correction.

# Output for the result. Must be a directory based on BIDS.
# Can override context.outDir or provide a specific directory.
# Not work when steps are present.
outputs:
  image_output:
    type: Directory
    doc: Output for the result, conform to BIDS standard.
    default: ${context.outDir}/label-initial
 ```

Assume we have a package manager named RDPM(Radiome Package Manager). To test a standalone workflow, we can create a yaml file `params1.yaml`

```yaml
non_local_means_filtering: True
n4_bias_field_correction: False
# mock resource pool.
resource_pool: 
    T1w:
        s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00008399/ses-BAS1/anat/sub-A00008399_ses-BAS1_T1w.nii.gz
# mock context.
context:
    workingDir: /outputs
```

Then we may run `rdpm run spec.yml params1.yml` and the result should reside in `outputs` defined in `spec.yml` . And it is convenient to have multiple parameters files for test.

Similarly, we could apply the same to a series of workflows. Assume we have a file `pipeline.yml`:

```yaml
radiomeSchemaVersion: v1.0

# Describe the type of schema and how to execute, required.
class: Workflow

# Name of the workflow. required.
name: anat-preproc

inputs:
  # Implicit, can be resolved either run-time or from file.
  resource_pool:
    type: ResourcePool
  context:
    type: Context
  non_local_means_filtering:
    type: boolean
    doc: enable non local means.
  n4_bias_field_correction:
    type: boolean
    doc: enable n4 bias correction.
  shrink_factor:
    type: float
    doc: shrink float for afni skullstrip.

steps:
  initial:
    run: initial/spec.yml
    in:
      non_local_means_filtering: ${inputs.non_local_means_filtering}
      n4_bias_field_correction: ${inputs.n4_bias_field_correction}
      # Mock context and resource pool is not allowed in steps.
      # There is only one mock opportunity on the top-level.
        
  skullstrip:
    run: skullstrip-afni/spec.yml
    in:
      shrink_factor: ${inputs.shrink_factor}
      avoid_vent: False
```

We can even compose a multi-level pipeline. But note that mocking context and resource pool is not allowed in `steps`. There is only one mock opportunity on the top-level to prevent possible abuse of the feature. To pass the parameters top-down, use `inputs ` and `${}` variable. The top-level inputs must be concrete exclusively. Also, there is only one global `outDir` in the `context`. Based on BIDS Extension, every workflow should put all result files in one separate directory under `context.outDir`.

Furthermore, if the Radiome CLI takes this yaml file and other command parameters as inputs, the CLI itself is equivalent to a program that generates `parameters.yml`, "mock" `resource_pool` and `context`, and eventually invoked `rdpm run spec.yml parameters.yml`. 

![pic](https://user-images.githubusercontent.com/2133226/74212244-f3d6e000-4c58-11ea-8c22-fe397bbe6877.png)

## CLI API and package management

We will have a Radiome Package Manager named `RDPM`, which supports

`rdpm init`

Initialize a workflow template using cookie-cutter.

`rdpm run path/to/spec.yml path/to/params.yml`

Run a workflow `spec` using the parameters from `params.yml`.

**Comment by anibalsolon** [comment]
Hi @puorc 

Thank you for compiling this, it seems really thorough! I believe there are two specs here: workflow spec and pipeline spec, correct? Pipeline as a set of connected workflows.

I do not think we could rely on the cwl-tool, only if we could submit the whole workflow in a generic format for radiome engine to execute.

For the file structure, I believe `spec.yml` should be inside the "package name" folder, to be pack together for Pypi, for example.
```
- doc
- test
- {{Package name}}
     - workflow.py
    - spec.yml
```

The mixed implementation looks good, maybe the 
```
  # Implicit, can be resolved either run-time or from file.
  resource_pool:
    type: ResourcePool
  context:
    type: Context
```
could be hidden from the spec, since they are implicit. For the template strings, Python now have the `{ variable }`, in comparison to the `${ javascript }` style. I am good with both, just bringing up to consideration.

In case of running a single workflow, since the workflows will be developed in Python, following a function signature etc, I guess the `spec.yml` should actually be the module name or `gh://...` pointing to the workflow python module, and it would gather the `spec.yml` from the module. So instead of `rdpm run spec.yml params1.yml`, we would have `rdpm run radiome.workflows.anat.initial params1.yml`. In the same sense, the 
```yaml
steps:
  initial:
    run: initial/spec.yml
```
would be
```yaml
steps:
  initial:
    run: radiome.workflows.anat.initial
```

**Comment by puorc** [comment]
Hi Anibal, thank you very much for the wonderful feedback!

Conceptually we will have two specs, one corresponds to the leaf node(workflow) and the other to the non-leaf node(pipeline). But the format is the same except that if there is `steps`(non-leaf node), `output` and `entry` will be ignored(leaf-node). 

I agree that we don't use cwl-tool. The effort to customize and maintain it surpasses the benefits significantly.  As the spec is a plain yaml file, it is not hard to make a lightweight parser for it.

The idea on the location of `spec.yml` and implicit `resourcepool` and `context` is nice! I am also thinking about not putting it in every inputs, and add special character in the input parameters file, such as @ResoucePool and @Context to distinguish from regular inputs.

As for spec.yml lookup, gh:// is a nice feature. But for the local files, I am not sure about the ways. Is the user expected to put the files in the correct location and provide names by himself or use a package manager like `rdpm install` to install it to a specific destination. We may discuss it.

**Comment by ccraddock** [comment]
The source of my confusion comes from not understanding why we have or need the spec.yml file, but after rereading and thinking about it I may understand.

In our early discussions of the workflow design, we specified methods that would check to make sure that all required parameters and resources are available before connecting the workflow. This functionality is likely to be very consistent across workflows, so it could be implemented once in a generic way. But this generic implementation will need to know what inputs the workflow needs in order to do this validation. This is the purpose of the spec.yml file.

Is that correct?

If so I think that everything is OK with this implementation. I agree with anibal on his points. But in general the 'Mixed Implementation' seems like the best approach.

I now also understand that the execution information isn't needed in the spec.yml file because we are requiring that the execution of each workflow to be the exact same, i.e. import the namespace, verify the inputs, call the create_workflow, and the execute the returned object. Correct?

**Comment by puorc** [comment]
For the second question, I think the procedure is always the same. We are somewhat emulating how the nipype works. The developer need to take care of create_workflow, which is to find the resource from the resource pool, connect the nipype or function interfaces, set the parameters, and put the output in the resource pool for further use. The pipeline builder will do the rest, such as load resources into resource pool, validate the inputs params against the schema in `spec.yml`, locate and execute the workflows. So the execution is the same for every single workflow as long as the developer follows the standard. 

For the first question, I can talk about how the idea evolves. For the first implementation, there was only a pipeline config yaml file for the pipeline builder to assemble the workflow and pass in the parameters. This is how the old version looks like.

```
# pipeline configuration .yaml (that will be validated with the schemas)
radiome.workflows.skullstripping.afni:
    spatial_normalization: yes
radiome.workflows.bias_field_correction:
    histogram_sharpening: 10.4
```

For a single workflow, there must be schema definition to validate the inputs. However, there are various validation libraries in Python and the schema definition can be very different. If we want to enforce a uniform format, we need to pick up one library or totally leave this problem to the developer. I choose cerberus because its schema only uses Python built-in types, which can be serialized without any difficulty. Therefore, a `schema.json` or `schema.yml` is necessary for every workflow. 

```python
schema = {
    'non_local_means_filtering': {'type': 'boolean'},
    'n4_bias_field_correction': {'type': 'boolean'}
}
```

Then I got some inspiration from CWL standard. At lease we need a place for descriptive information such as author, publication, etc. and also version control for template file in case of further extension. I borrowed the syntax from CWL and put the descriptive information, the template version and inputs schema into one file, which is the `spec.yml` file. 

```yaml
radiomeSchemaVersion: v1.0

# Describe the type of schema and how to execute, required.
class: Workflow

# Name of the workflow. required.
name: initial-processing

# A short descriptive documentation. optional.
doc: Reorient and resample the anatomical images.

# Other useful information. optional.
s:author:
 - class: s:Person
   s:identifier: https://id.org
   s:email: mailto:abc@gmail.com
   s:name: Somebody

s:contributor:
 - class: s:Person
   s:identifier: https://id.org
   s:email: mailto:dec@gmail.com
   s:name: Someone

s:citation: https://dx.doi.org/abcde
s:codeRepository: https://github.com/radiome/xxx.git
s:dateCreated: "2020-02-10"
s:license: https://spdx.org/licenses/Apache-2.0 

inputs:
 non_local_means_filtering:
   type: boolean
   doc: enable non local means.
 n4_bias_field_correction:
   type: boolean
   doc: enable n4 bias correction.
```

The pattern of CWL execution is `cwl-tool schema.yml parameters.ym;`, I found it a good fit for the mock. which is `radiome schema.yml test-parameters.yml`. Parameters like `n4_bias_field_correction` can be easily fit into a file. But mocking resource pool and context is also necessary. so I put them into `inputs` to indicate this fact.  

```yaml
inputs:
 # Implicit, can be resolved either run-time or from file.
 resource_pool:
   type: ResourcePool
 context:
   type: Context
   # Explicit.
 non_local_means_filtering:
   type: boolean
   doc: enable non local means.
 n4_bias_field_correction:
   type: boolean
   doc: enable n4 bias correction.
```

However, adding these two parameters in every pipeline is verbose, so I expect them to appear only in `parameters.yml` file but a special keyword is required to distinguish. 

 According to the BIDS standard, all files processed by this pipeline should be placed under a folder `outputdir/<pipeline-name>`, so the author of the pipeline need to provide such information. So I also added `outputs`. There might be multiple outputs and the author might want to place them in different folders. The author can access this information at runtime and specify how output node corresponds to output names.

```yaml
outputs:
 image_output:
   type: Directory
   doc: Output for the result, conform to BIDS standard.
   output_name: label-initial
 mask_output:
 	 type: Directory
 	 doc: Output for xx.
 	 output_name: mask-initial
```

I hope the author can also mock their `outputs` in the `parameters.yml` file, such that they can specify the any output location besides `outputdir` for further bash scripts or nipype workflows in ``parameters.yml``. So the mock file can be 

```yaml
non_local_means_filtering: True
n4_bias_field_correction: False
# mock resource pool.
resource_pool: 
    T1w:
        s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00008399/ses-BAS1/anat/sub-A00008399_ses-BAS1_T1w.nii.gz
# mock context.
context:
    workingDir: /outputs

outputs:
    image_output: /path/to/testoutput
    mask_output: /path/to/maskoutput
```

However, there must be a default value for pipeline building. Based on this fact, I come with up different ways.

```yaml
 image_output:
   type: Directory
   doc: Output for the result, conform to BIDS standard.
   default: ${context.outDir}/label-initial # More flexible in specifying outputs, can be any path
```

```yaml
 image_output:
   type: Directory
   doc: Output for the result, conform to BIDS standard.
   output_name: label-initial # optional, use the name field rom spec.yml if not exist. always under the context.output dir.
```

So far, we have a `spec.yml` file. However, I think we should have the same format for workflow and pipeline. So I transform

```yaml
# pipeline configuration .yaml (that will be validated with the schemas)
radiome.workflows.skullstripping.afni:
    spatial_normalization: yes
radiome.workflows.bias_field_correction:
    histogram_sharpening: 10.4
```

into

```yaml
radiomeSchemaVersion: v1.0

# Describe the type of schema and how to execute, required.
class: Workflow

# Name of the workflow. required.
name: anat-preproc

steps:
  initial:
    run: initial/spec.yml
    in:
      non_local_means_filtering: yes
      n4_bias_field_correction: 10.4
        
  skullstrip:
    run: skullstrip-afni/spec.yml
    in:
      shrink_factor: 1
      avoid_vent: False
```

From another perspetive, a pipeline can also be run in the same way as a single workflow `radiome pipeline.yml test-parameters.yml`

```yaml
inputs:
  non_local_means_filtering:
    type: boolean
    doc: enable non local means.
  n4_bias_field_correction:
    type: boolean
    doc: enable n4 bias correction.
  shrink_factor:
    type: float
    doc: shrink float for afni skullstrip.
  avoid_vent:
   	type: boolean
   	doc: avoid vent.

steps:
  initial:
    run: initial/spec.yml
    in:
      non_local_means_filtering: ${inputs.non_local_means_filtering}
      n4_bias_field_correction: ${inputs.n4_bias_field_correction}
        
  skullstrip:
    run: skullstrip-afni/spec.yml
    in:
      shrink_factor: ${inputs.shrink_factor}
      avoid_vent: ${inputs.avoid_vent}
```

where `parameters.yml`

```yaml
non_local_means_filtering: True
n4_bias_field_correction: False
shrink_factor: 1.0
avoid_vent: False
# mock resource pool.
resource_pool: 
    T1w:
        s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest/sub-A00008399/ses-BAS1/anat/sub-A00008399_ses-BAS1_T1w.nii.gz
# mock context.
context:
    workingDir: /outputs
```

Using this method, we can combine any workflows into a pipeline for testing purpose and provide the same infomation as testing a single workflow. And the pipeline can be a component of a higher-level pipeline because the yaml file format is all the same. This composition leads to a multi-level structure. 

Fusing these formats together, we finally get 

```yaml
inputs:
  non_local_means_filtering:
    type: boolean
    doc: enable non local means.
  n4_bias_field_correction:
    type: boolean
    doc: enable n4 bias correction.
  shrink_factor:
    type: float
    doc: shrink float for afni skullstrip.

steps:
  initial:
    run: initial/spec.yml
    in:
      non_local_means_filtering: ${inputs.non_local_means_filtering}
      n4_bias_field_correction: ${inputs.n4_bias_field_correction}
      # Mock context and resource pool is not allowed in steps.
      # There is only one mock opportunity on the top-level.
        
  skullstrip:
    run: skullstrip-afni/spec.yml
    in:
      shrink_factor: ${inputs.shrink_factor}
      avoid_vent: False
```

The field in steps must have a concrete value or abstract value from inputs, which can be read from its parents/grandparents, etc. or an external file. In pipeline building mode, the top-level pipeline will have all the concrete values and pass down to its children. It is also the entry point for execution. In testing mode, node with abstract values can run together with a `parameters.yml` file.
