### ISSUE TITLE
Wiki update mechanism

### ISSUE THREAD

**Issue by anibalsolon** [radiome-lab/radiome#58]
From what I understood in the action created to update the wiki, it will update the wiki at every new commit on whichever branch.

Would that be the case to limit it to the master branch?

```yaml
  push:
    branches:
      - master
```
